name: Publish (NPM & GPR)

# publish only when package json has changed - assuming version upgrade
on:
  push:
    branches: [main]
    paths: "packages/esbuild-plugin-ignoretests/package.json"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    defaults:
      run:
        working-directory: ./packages/esbuild-plugin-ignoretests

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org
      - run: sleep 3m
      - run: npm i -g pnpm && pnpm i
        name: Install dependencies
      - name: Publish to NPM
        run: |
          pnpm build && pnpm publish-package
          cd dist
          sed -i -e "s/\"name\": \"/\"name\": \"@mayank1513\//" package.json
          sed -i -e "s/pnpm add /pnpm add @mayank1513\//" README.md
          sed -i -e "s/npm install /npm install @mayank1513\//" README.md
          sed -i -e "s/yarn add /yan add @mayank1513\//" README.md
          sleep 30s
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          registry-url: https://npm.pkg.github.com/
      - name: Publish to GitHub Public Repository
        run: pnpm publish-package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
